### ISSUE TITLE
Validate Key Wrong Endpoint

### ISSUE THREAD

**Issue by sanzeeb3** [Make-Lemonade/lemonsqueezy-wp#22]
As per the docs https://docs.lemonsqueezy.com/help/licensing/license-api#post-v1-licenses-validate

But using the LS plugin. if any plugin e.g. [lemonsqueezy-wp-updater-example](https://github.com/Make-Lemonade/lemonsqueezy-wp-updater-example), tries to use the API URL: `https://example.com/wp-json/lsq/v1/validate`

It looks like LS plugin tries to use `/v1/users/me` endpoint instead.

which doesn't validate the license key.

**Expected behavior**
/validate endpoint should probably be used for validation.

**Software (please complete the following information):**
 - WordPress version: 6.1
 - PHP version: 7.4

**Additional context**
The issue is license counts toward each activation despite on the same site. We're supposed to use the /validate endpoint once activated.

For e.g. In the `lemonsqueezy-wp-updater-example` add a license key, change to wrong license key, enter the correct license key again. There can be 2 activation counts.

**Comment by gilbitron** [comment]
Hey @sanzeeb3. So the /validate endpoint is actually for validating an _API_ key, not a _license_ key. In the WP updater example, you can see in the [`class-settings-page` class](https://github.com/Make-Lemonade/lemonsqueezy-wp-updater-example/blob/main/includes/class-settings-page.php#L113) that it calls the plugin /activate and /deactivate endpoints only. 

This is because once you have a license key and instance ID, you can call the Lemon Squeezy [license API /validate endpoint](https://docs.lemonsqueezy.com/help/licensing/license-api) directly without having to use the WordPress plugin proxy.

**Comment by sanzeeb3** [comment]
> This is because once you have a license key and instance ID after calling the /activate endpoint, you can call the Lemon Squeezy [license API /validate endpoint](https://docs.lemonsqueezy.com/help/licensing/license-api) directly without having to use the WordPress plugin proxy.

but when we call the Lemon Squeezy [license API /validate endpoint](https://docs.lemonsqueezy.com/help/licensing/license-api) directly from the plugin (eg. WP Updater Example), we need an API key in the plugin? We can't distribute plugin with our API key.

While using /activate and /deactivate endpoints, we don't need API key - because it's generated by WordPress plugin proxy in our site.

**Comment by sanzeeb3** [comment]
> In the WP updater example, you can see in the [class-settings-page class](https://github.com/Make-Lemonade/lemonsqueezy-wp-updater-example/blob/main/includes/class-settings-page.php#L113) that it calls the plugin /activate and /deactivate endpoints only.

This is where the actual issue is. If you activate the same license key multiple times from a single site - each activation counts towards the limit. So, we need a license key validate/ endpoint here?

**Comment by gilbitron** [comment]
> but when we call the Lemon Squeezy [license API /validate endpoint](https://docs.lemonsqueezy.com/help/licensing/license-api) directly from the plugin (eg. WP Updater Example), we need an API key in the plugin?

You don't need to authenticate calls to the license API endpoints. They don't require an API key.
