### ISSUE TITLE
Plugin updater doesn't seem to work

### ISSUE THREAD

**Issue by sanzeeb3** [Make-Lemonade/lemonsqueezy-wp#23]
**Describe the bug**
When using LS Example Plugin Updater, the updates never arrived with the error:

`[body] => {"success":false,"error":"Error fetching license_key","error_code":"error_fetching_license_key"}`

the activation/deactivation worked fine.

While looking into LS plugin, here:

https://github.com/Make-Lemonade/lemonsqueezy-wp/blob/develop/src/class-lsq-updater.php

`get_license()`  returned the license object fine.

```
[25-Jan-2023 08:07:43 UTC] stdClass Object
(
    [valid] => 1
    [error] => 
    [license_key] => stdClass Object
        (
            [id] => 20772
            [status] => active
            [key] => f20c53e0-2798-48dc-974c-36d216200a26
            [activation_limit] => 7
            [activation_usage] => 4
            [created_at] => 2023-01-19 07:18:18
            [expires_at] => 2025-01-19 00:00:00
            [test_mode] => 1
        )

    [instance] => 
    [meta] => stdClass Object
        (
            [store_id] => 12735
            [order_id] => 373446
            [order_item_id] => 373686
            [product_id] => 42204
            [variant_id] => 36955
        )

)
```

but, `get_license_key()` resulted in the response error. Which caused the error:

**To Reproduce**
1. Install the LS Updater Example Plugin https://github.com/Make-Lemonade/lemonsqueezy-wp-updater-example
2. Add a LS in the settings.
3. Add new version plugin in LS.
4. The plugin update doesn't appear in the dashboard.

**Software (please complete the following information):**
 - Plugin version: 1.2.2
 - WordPress version: 6.1
 - PHP version: 7.4
 - Browser: Chrome
 
**Additional context**

**Comment by gilbitron** [comment]
@sanzeeb3 What was the error you received from `get_license_key`?

**Comment by sanzeeb3** [comment]
@gilbitron `404` Error was the response. https://api.lemonsqueezy.com/v1/license-keys/20772/?include=store,product,order-item - the URL.

**Comment by gilbitron** [comment]
Ah, this is a test mode license key. Unfortunately, our WordPress plugin doesn't support authenticating with test mode at the moment so any calls to the full API (not the license API) will fail. See #18.

**Comment by johannheyne** [comment]
This issue occurred to me a few days ago but with real client licenses.
